Simplified drill install by using minio VIP.
dcos/demos pull request #29
Opened 2017-08-06 23:51 UTC by joerg84

2017-08-06 23:53 UTC, joerg84 commented
This depends on the following universe PR: https://github.com/mesosphere/universe/pull/1338

Also when testing, please consider that the dcos marathon app command will reference the old version (until this PR is commited). Just use the local file (or copy past the AppDefinition in the UI).

2017-08-07 17:37 UTC, pleia2 requested changes
One comment inline about consistency.

And when I tested this, Drill gave me an error back:

org.apache.drill.common.exceptions.UserRemoteException: SYSTEM ERROR: UnknownHostException: test.minio.marathon.l4lb.thisdcos.directory: unknown error [Error Id: 9cb51213-f912-4146-ac06-ede011f46a4a on ip-10-0-1-151.us-west-2.compute.internal:31010]

2017-08-07 17:37 UTC, pleia2 commented on applogs/1.9/README.md
> +dcos marathon app add https://raw.githubusercontent.com/dcos/demos/master/applogs/1.9/drill/apache-drill.json
If we want to be consistent with other instructions, we should instead use:

$ cd $DEMO_HOME/applogs/1.9/
$ dcos marathon app add drill/apache-drill.json

2017-08-07 17:47 UTC, pleia2 commented on applogs/1.9/README.md
> +dcos marathon app add https://raw.githubusercontent.com/dcos/demos/master/applogs/1.9/drill/apache-drill.json
Oops, didn't include the universe patch that the PR requires.

2017-08-07 17:49 UTC, joerg84 commented on applogs/1.9/README.md
> +dcos marathon app add https://raw.githubusercontent.com/dcos/demos/master/applogs/1.9/drill/apache-drill.json
You need to include the changed universe universe PR...

2017-08-07 17:50 UTC, joerg84 commented on applogs/1.9/README.md
> +dcos marathon app add https://raw.githubusercontent.com/dcos/demos/master/applogs/1.9/drill/apache-drill.json
I hope to get to a point where you don't need to checkout the repo...
Hence, the marathon app add from github

2017-08-07 17:51 UTC, pleia2 commented on applogs/1.9/README.md
> +dcos marathon app add https://raw.githubusercontent.com/dcos/demos/master/applogs/1.9/drill/apache-drill.json
Ah, gotcha.

2017-08-07 18:50 UTC, pleia2 commented on applogs/1.9/README.md
> +dcos marathon app add https://raw.githubusercontent.com/dcos/demos/master/applogs/1.9/drill/apache-drill.json
Error still occurs even once we have the Minio VIP working, @joerg84 investigating.

2017-08-08 13:41 UTC, mattj-io commented
testing

2019-12-18 17:12 UTC, yankcrime commented
Closing as stale.

2019-12-18 17:12 UTC, closed without merging